---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: code

services:
  - name: database
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: dream_deeply_test
      MYSQL_USER: dream_deeply
      MYSQL_PASSWORD: integration
      MYSQL_ROOT_PASSWORD: root_integration

steps:
  - name: mod-download
    pull: if-not-exists
    image: golang:1.14
    commands:
      - go mod download
    environment:
      GO11MODULE: on
    when:
      event:
        - push
  
  - name: test
    pull: if-not-exists
    image: golang:1.14
    commands:
      - make test-drone
    environment:
      GOPATH: /go
    when:
      event:
        - push
...